#!/bin/sh
# Usage: unhost filename
#
# unhost: convert mainframe-formatted files
#   1. Remove line sequence numbers (cols 73 - 80)
#   2. Convert ASA (printer) chars in column 1 to spaces
#       - except line 1 (*PROCESS)
#       (*PROCESS after line 1 will need to done by hand)
#   3. Strip trailing spaces
#	4. Writes the result of the conversion to stdout.
#
#    Copyright 2004 Rob Watson
#    Copyright 2006 Henrik Sorensen
#
# This file is part of GCC front-end for the PL/I programming language, GCC
# PL/I
#
# GCC PL/I is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2.
#
# GCC PL/I is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GCC PL/I; see the file COPYING.  If not, write to
# the Free Software Foundation, 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

#cat $1 | colrm 73 80 | sed "2,$ s/^./ /g" | sed "s/ *$//g" > __temp

cat $1 | colrm 73 80 | sed "s/^[-10+]/ /g" | sed "s/ *$//g"
